language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - DJANGO=django==2.2.12
  - DJANGO=django==3.0.5

services:
  - postgresql
  - mysql

 matrix:
  - DB=pgsql
  - DB=mysql


before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS travis_ci_test;'; fi"

# command to install dependencies
install:
  - pip install -e .
  - pip install $DJANGO
  - pip install codecov

script:
  - coverage run --include=../* runtests.py

after_success:
  - codecov
