language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"


  global:
    - PYTHONWARNINGS=default,ignore::PendingDeprecationWarning,ignore::ResourceWarning
    - DJANGO_DATABASE_USER_POSTGRES=postgres
    - DJANGO_DATABASE_USER_MYSQL=travis
  matrix:
    - DJANGO='>=3.0,<3.1'
    - DJANGO='>=2.2,<3.0'
    - DJANGO='>=2.1,<2.2'

matrix:
  fast_finish: true

addons:
  apt:
    packages:
      - libmysqlclient-dev
services:
  - postgresql
  - mysql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS travis_ci_test;'; fi"

# command to install dependencies
install:
  - pip install -e .
  - pip install $DJANGO
  - pip install codecov

script:
  - coverage run --include=../* runtests.py

after_success:
  - codecov
