language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - DJANGO=django==2.2.17
  - DJANGO=django==3.0.11
  - DJANGO=django==3.1.4


# command to install dependencies
install:
  - pip install -e .
  - pip install $DJANGO
  - pip install codecov

script:
  - coverage run --include=../* runtests.py

after_success:
  - codecov
